# Generated by Django 4.0.4 on 2022-06-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipoProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código del tipo de producto')),
                ('nombreTipo', models.CharField(max_length=20, verbose_name='Tipo del producto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código del tipo de usuario')),
                ('nombreTipoUsuario', models.CharField(max_length=20, verbose_name='Tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('nombreUsuario', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Nombre del usuario')),
                ('apellidoUsuario', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Apellido del usuario')),
                ('claveUsuario', models.CharField(max_length=30, verbose_name='Clave del usuario')),
                ('emailUsuario', models.CharField(max_length=50, verbose_name='Email del usuario')),
                ('telefonoUsuario', models.IntegerField(blank=True, default=None, null=True, verbose_name='Telefono del usuario')),
                ('direccionUsuario', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Direccion del usuario')),
                ('regionUsuario', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Region del usuario')),
                ('comunaUsuario', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Comuna del usuario')),
                ('codigoPostalUsuario', models.IntegerField(blank=True, default=None, null=True, verbose_name='Codigo postal Usuario')),
                ('tipoUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tienda.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del producto')),
                ('cantidadProducto', models.IntegerField(verbose_name='Cantidad del producto')),
                ('descripcionProducto', models.CharField(max_length=500, verbose_name='Descripcion del producto')),
                ('foto', models.ImageField(null=True, upload_to='Productos')),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.tipoproducto')),
            ],
        ),
    ]
