# Generated by Django 4.0.4 on 2022-05-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigoPostalUsuario',
            field=models.IntegerField(verbose_name='Codigo postal Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comunaUsuario',
            field=models.CharField(max_length=50, verbose_name='Comuna del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='emailUsuario',
            field=models.CharField(max_length=50, verbose_name='Email del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='regionUsuario',
            field=models.CharField(max_length=50, verbose_name='Region del usuario'),
        ),
    ]
