# Generated by Django 4.0.4 on 2022-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_usuario_codigopostalusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(null=True, upload_to='Productos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccionUsuario',
            field=models.CharField(max_length=50, verbose_name='Direccion del usuario'),
        ),
    ]
